### ISSUE TITLE
How to run for active ROS image topic instead of using image files?

### ISSUE THREAD

**Issue by erinline** [laxnpander/OpenREALM_ROS1_Bridge#6]
I am trying to repurpose this node to run on a live ROS image topic (type: sensor_msgs/Image), so I assume I need to replace the exiv2_grabber_node with ros_grabber_node, but an example of how to do so would be helpful. I tried copying the exiv2 node launch and replacing it with ros node launch, resulting in the following launch file:

          <launch>
              <arg name="camera_id" default="downward_cam"/>
              <arg name="topic_adapter" default="$(arg camera_id)/camera/image"/>
              <arg name="topic_pose_est" default="/realm/$(arg camera_id)/pose_estimation/frame"/>
              <arg name="topic_dense" default="/realm/$(arg camera_id)/densification/frame"/>
              <arg name="topic_surf" default="/realm/$(arg camera_id)/surface_generation/frame"/>
              <arg name="topic_rect" default="/realm/$(arg camera_id)/ortho_rectification/frame"/>
              <arg name="topic_mosaic" default="/realm/$(arg camera_id)/mosaicing/frame"/>
              <arg name="topic_out_frame" default="/realm/$(arg camera_id)/out/frame"/>
          
              <node pkg="realm_ros" type="realm_ros_grabber" name="realm_ros_grabber" output="screen">
                  <param name="config/id" type="string" value="$(arg camera_id)"/>
                  <param name="config/input" type="string" value="$(arg topic_adapter)"/>
                  <param name="config/rate" type="double" value="10.0"/>
                  <param name="topic/out/frame" type="string" value="$(arg topic_out_frame)"/>
                  <param name="config/profile" type="string" value="alexa_gnss"/>
                  
                  
                  
                  
              </node>
          
              <node pkg="realm_ros" type="realm_stage_node" name="realm_pose_estimation" output="screen">
                  <param name="stage/type" type="string" value="pose_estimation"/>
	          <param name="stage/master" type="bool" value="true"/>
                  <param name="topics/input/frame" type="string" value="$(arg topic_out_frame)"/>
                  <param name="topics/output" type="string" value="$(arg topic_pose_est)"/>
                  <param name="config/id" type="string" value="$(arg camera_id)"/>
                  <param name="config/profile" type="string" value="alexa_gnss"/>
                  <param name="config/method" type="string" value="open_vslam"/>
                  
                  
              </node>
          
              <node pkg="realm_ros" type="realm_stage_node" name="realm_surface_generation" output="screen">
                  <param name="stage/type" type="string" value="surface_generation"/>
                  <param name="topics/input/frame" type="string" value="$(arg topic_out_frame)"/>
                  <param name="topics/output" type="string" value="$(arg topic_surf)"/>
                  <param name="config/id" type="string" value="$(arg camera_id)"/>
                  <param name="config/profile" type="string" value="alexa_gnss"/>
                  
                  
              </node>
          
              <node pkg="realm_ros" type="realm_stage_node" name="realm_ortho_rectification" output="screen">
                  <param name="stage/type" type="string" value="ortho_rectification"/>
                  <param name="topics/input/frame" type="string" value="$(arg topic_surf)"/>
                  <param name="topics/output" type="string" value="$(arg topic_rect)"/>
                  <param name="config/id" type="string" value="$(arg camera_id)"/>
                  <param name="config/profile" type="string" value="alexa_gnss"/>
                  
                  
              </node>
          
              <node pkg="realm_ros" type="realm_stage_node" name="realm_mosaicing" output="screen">
                  <param name="stage/type" type="string" value="mosaicing"/>
                  <param name="topics/input/frame" type="string" value="$(arg topic_rect)"/>
                  <param name="config/id" type="string" value="$(arg camera_id)"/>
                  <param name="config/profile" type="string" value="alexa_gnss"/>
                  
                  
              </node>
          
              <node name="rviz" pkg="rviz" type="rviz" args="-d $(find realm_ros)/rviz/realm.rviz" />
          
          </launch>
However, the ros grabber node crashes. What do I need to change?

**Comment by erinline** [comment]
Just noticed this error prints a little while before crash:

             [ INFO] [1650725492.622501147]: ROS Grabber Node successfully loaded camera: 
	        fps = 10
	        cx = 610.324
	        cy = 516.917
	        fx = 1209.07
	        fy = 1210.66
	        k1 = -0.198806
	        k2 = 0.122544
	        p1 = -0.000221
	        p2 = -0.000877
	        k3 = 0
        terminate called after throwing an instance of 'ros::ConflictingSubscriptionException'
          what():  Tried to subscribe to a topic with the same name but different md5sum as a topic that was already subscribed [sensor_msgs/Imu/6a62c6daae103f4ff57a132d6f95cec2 vs. std_msgs/Float64/fdb28210bfa9d7c91146260178d9a584]

**Comment by laxnpander** [comment]
@erinline Hey, the problem with running it with an image topic is that OpenREALM expects GNSS, heading and relative altitude above ground as well. An image alone is not sufficient. Here is an example how to launch the ros_grabber_node correctly:

```c
    <node pkg="realm_ros" type="realm_ros_grabber" name="realm_ros_grabber" output="screen">
        <param name="config/id" type="string" value="$(arg camera_id)"/>
        <param name="config/profile" type="string" value="alexa_gnss"/>
        <param name="topic/image" type="string" value="$(arg topic_in_image)"/>
        <param name="topic/gnss" type="string" value="$(arg topic_in_gnss)"/>
        <param name="topic/heading" type="string" value="$(arg topic_in_heading)"/>
        <param name="topic/relative_altitude" type="string" value="$(arg topic_in_relative_altitude)"/>
        <param name="topic/orientation" type="string" value="$(arg topic_in_orientation)"/>
        <param name="topic/out/frame" type="string" value="$(arg topic_out_adapter_frame)"/>
	<!--param name="topic/out/imu" type="string" value="$(arg topic_out_adapter_imu)"/-->
    </node>

```
Info: The additional sensor data is required to georeference the visual SLAM poses. You could "hack" some reasonable values, though I'd recommend to use real sensor inputs if you have them.

**Comment by laxnpander** [comment]
Reopen if there are open questions left.
